sudo: required
services:
  - docker

before_install:
  - docker build -t simmonson/docker-cicd-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true simmonson/docker-cicd-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-cicd-aws"
  env: "DockerCicdAws-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-720252850272"
  bucket_path: "docker-cicd-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY